const data = {
  products: [
    {
      name: 'Compostera Negra Un Cajon',
      slug: 'compostera-n1cajon',
      category: 'Composteras',
      image: '/images/cajon-negro/cajon-negro.jpg',
      imageb: '/images/cajon-negro/cajon-negrob.jpg',
      price: 60,
      brand: 'Cultivate',
      rating: 9,
      numReviews: 8,
      countInStock: 2,
      description: 'Plástico reciclado, un cajon',
    },
    {
      name: 'Compostera Negra Dos Cajones',
      slug: 'compostera-n2cajon',
      category: 'Composteras',
      image: '/images/compo-negra-2cj/compo-negra-2cj.jpg',
      price: 80,
      brand: 'Cultivate',
      rating: 5,
      numReviews: 10,
      countInStock: 20,
      description: 'Plástico reciclado, dos cajones',
    },
    {
      name: 'Compostera Negra Tres Cajones',
      slug: 'compostera-n3cajon',
      category: 'Composteras',
      image: '/images/compo-negra-3cj/compo-negra-3cj.jpg',
      price: 100,
      brand: 'Cultivate',
      rating: 4,
      numReviews: 12,
      countInStock: 13,
      description: 'Plástico reciclado, tres cajones',
    },
    {
      name: 'Compostera Negra Cuatro Cajones',
      slug: 'compostera-n4cajon',
      category: 'Composteras',
      image: '/images/compo-negra-4cj/compo-negra-4cj.jpg',
      price: 120,
      brand: 'Cultivate',
      rating: 6,
      numReviews: 15,
      countInStock: 9,
      description: 'Plástico reciclado, cuatro cajones',
    },
    {
      name: 'Compostera Blanca Un Cajon',
      slug: 'compostera-b1cajon',
      category: 'Composteras',
      image: '/images/cajon-blanco/cajon-blanco.jpg',
      price: 60,
      brand: 'Cultivate',
      rating: 9,
      numReviews: 12,
      countInStock: 15,
      description: 'Plástico reciclado, un cajon',
    },
    {
      name: 'Compostera Blanca Dos Cajones',
      slug: 'compostera-b2cajon',
      category: 'Composteras',
      image: '/images/compo-blanca-2cj/compo-blanco-2cj.jpg',
      price: 80,
      brand: 'Cultivate',
      rating: 5,
      numReviews: 10,
      countInStock: 20,
      description: 'Plástico reciclado, dos cajones',
    },
    {
      name: 'Compostera Blanca Tres Cajones',
      slug: 'compostera-b3cajon',
      category: 'Composteras',
      image: '/images/compo-blanca-3cj/compo-blanca-3cj.jpg',
      price: 100,
      brand: 'Cultivate',
      rating: 6,
      numReviews: 13,
      countInStock: 19,
      description: 'Plástico reciclado, tres cajones',
    },
    {
      name: 'Compostera Blanca Cuatro Cajones',
      slug: 'compostera-b4cajon',
      category: 'Composteras',
      image: '/images/compo-blanca-4cj/compo-blanca-4cj.jpg',
      price: 120,
      brand: 'Cultivate',
      rating: 8,
      numReviews: 15,
      countInStock: 19,
      description: 'Plástico reciclado, cuatro cajones',
    },
    {
      name: 'Compostera Madera Balcon',
      slug: 'compostera-madera',
      category: 'Composteras',
      image: '/images/compo-madera-balcon/compos-madera-balcon.jpg',
      price: 200,
      brand: 'Creavida',
      rating: 8,
      numReviews: 15,
      countInStock: 20,
      description: 'Madera reciclada, de balcon',
    },
    {
      name: 'Compostera Madera Piso',
      slug: 'compostera-piso',
      category: 'Composteras',
      image: '/images/compo-madera-piso/compo-madera-piso.jpg',
      price: 180,
      brand: 'Creavida',
      rating: 9,
      numReviews: 12,
      countInStock: 15,
      description: 'Madera reciclada, de piso',
    },
    {
      name: 'Palita de Mano',
      slug: 'accesorios-siembra',
      category: 'Accesorios',
      image: '/images/palita-de-mano/PaladeMano.jpg',
      price: 50,
      brand: 'Acerosdejardin',
      rating: 10,
      numReviews: 8,
      countInStock: 20,
      description: 'Palita de mano de acero inoxidable',
    },
    {
      name: 'Tamiz',
      slug: 'accesorio-tamiz',
      category: 'Accesorios',
      image: '/images/tamiz/tamiz.jpg',
      price: 60,
      brand: 'Acerosdejardin',
      rating: 7,
      numReviews: 20,
      countInStock: 10,
      description: 'Malla de acero inoxidable',
    },
    {
      name: 'Aireador',
      slug: 'accesorios-aireador',
      category: 'Accesorios',
      image: '/images/aireador/aireador.jpg',
      price: 50,
      brand: 'Acerosdejardin',
      rating: 10,
      numReviews: 8,
      countInStock: 20,
      description: 'Aereador para flujo de aire en composta',
    },
    {
      name: 'Kit Nuevos Agricultores',
      slug: 'kit-siembra',
      category: 'Kit',
      image: '/images/kit-nuevos-agri/kit-nuevos-agri.jpeg',
      price: 250,
      brand: 'Creavida',
      rating: 10,
      numReviews: 20,
      countInStock: 20,
      description: 'Kit para iniciarte en la siembra',
    },
    {
      name: 'Kit Protege tus Semillas',
      slug: 'kit-semilla',
      category: 'Kit',
      image: '/images/kit-prote-semillas/kit-prote-semillas.jpg',
      price: 250,
      brand: 'Creavida',
      rating: 8,
      numReviews: 10,
      countInStock: 20,
      description: 'Kit para proteger las semillas',
    },
    {
      name: 'Combo Inclusion',
      slug: 'compo-huerta',
      category: 'Combo',
      image: '/images/combo-inclusion/COMBO-IS.jpg',
      price: 350,
      brand: 'Creavida',
      rating: 10,
      numReviews: 20,
      countInStock: 20,
      description: 'Combo composta básica con huerta',
    },
    {
      name: 'Huerta Mediana',
      slug: 'huerta',
      category: 'huerta',
      image: '/images/huerta-mediana/huerta-mediana.jpg',
      price: 300,
      brand: 'Creavida',
      rating: 10,
      numReviews: 10,
      countInStock: 20,
      description: 'Huerta mediana para interiores',
    },
    {
      name: 'Pala Ancha',
      slug: 'accesorios-pala',
      category: 'Accesorios',
      image: '/images/pala-ancha/Pala-Anchab.jpg',
      price: 100,
      brand: 'Acerosdejardin',
      rating: 8,
      numReviews: 5,
      countInStock: 20,
      description: 'Huerta mediana para interiores',
    },
    {
      name: 'Compostera Giratoria 4kg',
      slug: 'compostera-gira4',
      category: 'Composteras',
      image: '/images/dc-40/dc-40.jpg',
      price: 195,
      brand: 'Creavida',
      rating: 10,
      numReviews: 12,
      countInStock: 15,
      description: 'Plástico reciclado, 1 a 2 personas',
    },
    {
      name: 'Compostera Giratoria 8kg',
      slug: 'compostera-gira8',
      category: 'Composteras',
      image: '/images/dc-80/dc-80.jpg',
      price: 220,
      brand: 'Creavida',
      rating: 10,
      numReviews: 12,
      countInStock: 15,
      description: 'Plástico reciclado, 2 a 4 personas',
    },
    {
      name: 'Compostera Giratoria 10kg',
      slug: 'compostera-gira10',
      category: 'Composteras',
      image: '/images/ks-100/ks-100.jpg',
      price: 280,
      brand: 'Creavida',
      rating: 10,
      numReviews: 12,
      countInStock: 15,
      description: 'Plástico reciclado, 3 0 6 personas',
    },
  ],
};

export default data;
